{
  wayland.windowManager.hyprland = {
    enable = true;
    packages = null;
    portalPackage = null;

    systemd.variables = [ "--all" ];

    settings = {
      "$mod" = "SUPER";

      # TODO: Find better way to apply themes or autoricing features
      # Wallust autogenerated variables
      "$background" = "rgb(2D2D30)";
      "$foreground" = "rgb(EFF5EC)";
      "$color0" = "rgb(525255)";
      "$color1" = "rgb(252630)";
      "$color2" = "rgb(424B48)";
      "$color3" = "rgb(415972)";
      "$color4" = "rgb(5F7060)";
      "$color5" = "rgb(637563)";
      "$color6" = "rgb(9DAA96)";
      "$color7" = "rgb(E0E8DB)";
      "$color8" = "rgb(9CA399)";
      "$color9" = "rgb(323340)";
      "$color10" = "rgb(586460)";
      "$color11" = "rgb(567697)";
      "$color12" = "rgb(7E957F)";
      "$color13" = "rgb(849C84)";
      "$color14" = "rgb(D1E3C8)";
      "$color15" = "rgb(E0E8DB)";

      exec-once = [
        "swww-daemon --format xrgb"
        "waybar"
        "nm-applet --indicator"
        "blueman-applet"
        "swaync"
        "fcitx5 -d -r"
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "pypr"
        "corectrl --minimize-systray"
      ];
    };
  };
}
